
---

  - name: Copying the configuration file
    template:
      src: sensu.conf.j2
      dest: /etc/logstash/conf.d/sensu.conf
      owner: logstash
      group: logstash
      mode: 0640
    notify: Restart Logstash client
    tags: configure

  - name: Starting the Logstash client
    systemd:
      name: logstash
      state: started
      enabled: yes

